version: '3.8'

services:
  web:
    build: .
    volumes:
      - megacodist.com-code:/webapp
      - megacodist.com-assets:/webapp/assets
      - megacodist.com-media:/webapp/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings

volumes:
  megacodist.com-code:
    external: true
  megacodist.com-assets:
    external: true
  megacodist.com-media:
    external: true
