# Using the official Python image as a base...
FROM python:3.12-slim

# Avoiding writing .pyc files...
ENV PYTHONDONTWRITEBYTECODE=1

# Ensuring output is logged to Docker in real-time...
ENV PYTHONUNBUFFERED=1

# Setting working directory...
WORKDIR /webapp

# Making port 8000 available to the world outside this container...
EXPOSE 8000

# Installing dependencies...
COPY requirements.txt /webapp/
RUN pip install --no-cache-dir -r requirements.txt

# Running Django's server...
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
